CREATE TABLE IF NOT EXISTS accounts (
  id SERIAL PRIMARY KEY, 
  name VARCHAR (50) UNIQUE NOT NULL, 
  password VARCHAR (50) NOT NULL, 
  email VARCHAR (255) UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS posts (
  id SERIAL PRIMARY KEY, 
  title VARCHAR (100) UNIQUE NOT NULL, 
  content VARCHAR (300) NOT NULL, 
  author_id INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);